# Generated by Django 3.2.8 on 2022-05-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contract_ID', models.CharField(blank=True, max_length=12, null=True)),
                ('Initials', models.CharField(blank=True, max_length=4, null=True)),
                ('ID_Number', models.CharField(blank=True, max_length=13, null=True)),
                ('Surname', models.CharField(blank=True, max_length=50, null=True)),
                ('Premium', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Name_of_Bank', models.CharField(blank=True, choices=[('Investec', 'Investec'), ('ABSA', 'ABSA'), ('CAPITEC', 'CAPITEC'), ('STANDARD_BANK', 'STANDARD_BANK'), ('FNB', 'FNB'), ('NEDBANK', 'NEDBANK')], max_length=20, null=True)),
                ('Name_of_Branch', models.CharField(blank=True, choices=[('470010', '470010'), ('250655', '250655'), ('51001', '51001'), ('198765', '198765'), ('580105', '580105'), ('632005', '632005')], max_length=20, null=True)),
                ('Name_of_Type', models.CharField(blank=True, choices=[('SAVING', '2'), ('CURRENT', '1'), ('TRANSACTION', '3')], max_length=20, null=True)),
            ],
        ),
    ]
