# Generated by Django 3.2.8 on 2022-05-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('May_4_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_model',
            name='Name_of_Bank',
            field=models.CharField(blank=True, choices=[('NEDBANK', 'NEDBANK'), ('CAPITEC', 'CAPITEC'), ('ABSA', 'ABSA'), ('FNB', 'FNB'), ('Investec', 'Investec'), ('STANDARD_BANK', 'STANDARD_BANK')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract_model',
            name='Name_of_Branch',
            field=models.CharField(blank=True, choices=[('51001', '51001'), ('198765', '198765'), ('470010', '470010'), ('580105', '580105'), ('632005', '632005'), ('250655', '250655')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract_model',
            name='Name_of_Type',
            field=models.CharField(blank=True, choices=[('TRANSACTION', '3'), ('SAVING', '2'), ('CURRENT', '1')], max_length=20, null=True),
        ),
    ]
